package com.lusifer.cloud.domain;

public class Roles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.username
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.username
     *
     * @return the value of roles.username
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.username
     *
     * @param username the value for roles.username
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role
     *
     * @return the value of roles.role
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role
     *
     * @param role the value for roles.role
     *
     * @mbggenerated Mon Mar 23 12:00:12 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}